#this is for binder
name: pycoa-environment
channels:
  - conda-forge
dependencies:
  - firefox
  - python
  - numpy
  - selenium 
  - geckodriver 
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - matplotlib
    - bokeh
    - branca
    - bs4
    - datascroller
    - datetime
    - folium
    - lxml
    - pandas==1.4.2
    - geopandas
    - matplotlib
    - numpy
    - pycountry
    - pycountry_convert
    - requests
    - scipy
    - shapely
    - pytest
    - unidecode
    - openpyxl 

