name: pycoa-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - bokeh
    - branca
    - bs4
    - datascroller
    - datetime
    - folium ~=0.12.1
    - lxml
    - geopandas
    - matplotlib
    - numpy
    - pandas
    - pycountry
    - pycountry_convert
    - requests
    - scipy
    - shapely
    - pytest >=5.0
    - unidecode
