#this is for binder
name: pycoa-environment
channels:
  - conda-forge
dependencies:
  - firefox
  - python=3.9
  - numpy
  - selenium 
  - geckodriver
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - matplotlib
    - bokeh==2.3.3
    - branca
    - bs4
    - datascroller
    - datetime
    - folium
    - lxml
    - pandas==1.3.5
    - geopandas==0.10.2
    - matplotlib
    - numpy
    - pycountry
    - pycountry_convert
    - requests
    - scipy
    - shapely==1.8.2
    - pytest
    - unidecode
    - openpyxl 
    - pygdal 
