import tweepy
'''
Python script to automatically post a text or image
You have to put your keys in the variables just below, to find the keys it's here: https://developer.x.com/en/portal/dashboard
If you can't find them watch this video : https://www.youtube.com/watch?v=BdmUhQnPToM&list=PLTqHuV0gIyxq_Wix5AbtirmUkkmJplEYn&index=1
'''

'''
for the moment the scripts works with the plot generated by interactive.py'''
# Keys
api_key = "API_KEY"
api_secret_key = "API_SECRET_KEY"
access_token = "ACCESS_TOKEN"
access_token_secret = "ACCESS_TOKEN"
bearer_token = r"BEARER_TOKEN"

# Authentification
client = tweepy.Client(bearer_token=bearer_token,
                       consumer_key=api_key,
                       consumer_secret=api_secret_key,
                       access_token=access_token,
                       access_token_secret=access_token_secret)
#v1.1
auth = tweepy.OAuth1UserHandler(api_key, api_secret_key, access_token, access_token_secret)
api = tweepy.API(auth)

# Fonction pour poster un tweet
def poster_tweet(message):
    try:
        response = client.create_tweet(text=message)
        print("Tweet posté avec succès !", response.data)
        print(response.data['id'])
    except tweepy.TweepyException as e:
        print(f"Une erreur est survenue : {e}")

# Fonction pour poster un tweet avec une image
def tweet_image(message, image_path):
    try:
        media = api.media_upload(image_path)
        response = client.create_tweet(text=message, media_ids=[media.media_id_string])
        print("Tweet avec image envoyé avec succès !", response.data)
    except tweepy.TweepyException as e:
        print(f"Une erreur est survenue : {e}")

text= "Ce tweet est généré automatiquement."
poster_tweet(text)
tweet_image("Voici un tweet avec une image !", "fig/plot.png")