name : CI

on:
  push:
  pull_request:
    branches:
      - main


jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: 
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    
    
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name : Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies on Ubuntu and macOS
        if: runner.os != 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install --only-binary :all: numpy==1.23.2 \
            bokeh==2.4.0 \
            branca \
            bs4 \
            datascroller \
            folium~=0.12.1 \
            geopandas==0.10.2 \
            matplotlib \
            pandas==1.4.2 \
            pycountry \
            pycountry_convert \
            requests \
            scipy \
            shapely \
            pytest>=5.0 \
            pandas-flavor \
            openpyxl \
            unidecode \
            lxml \
            colorama \
            tqdm \
            seaborn \
            IPython

      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.23.2 \
            bokeh==2.4.0 \
            branca \
            bs4 \
            datascroller \
            folium~=0.12.1 \
            geopandas==0.10.2 \
            matplotlib \
            pandas==1.4.2 \
            pycountry \
            pycountry_convert \
            requests \
            scipy \
            shapely \
            pytest>=5.0 \
            pandas-flavor \
            openpyxl \
            unidecode \
            lxml \
            colorama \
            tqdm \
            seaborn \
            IPython


      - name: Run tests
        run: pytest
