name : CI

on:
  push:
    branches:
      - main
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: 
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"
          - "pypy-3.7"
          - "pypy-3.8"
          - "pypy-3.9"
    
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name : Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install \
            bokeh==2.4.0 \
            branca \
            bs4 \
            datascroller \
            folium~=0.12.1 \
            geopandas==0.10.2 \
            matplotlib \
            numpy \
            pandas==1.4.2 \
            pycountry \
            pycountry_convert \
            requests \
            scipy \
            shapely \
            pytest>=5.0 \
            pandas-flavor \
            openpyxl \
            unidecode \
            openpyxl \
            lxml \
            colorama \
            pytest


      - name: Run tests
        run: pytest
