name : CI

on:
  push:
  pull_request:
    branches:
      - main


jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: 
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    
    
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name : Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies on Ubuntu and macOS
        if: runner.os != 'Windows'
        run: |
          python -m pip install \
            bokeh==2.4.0 \
            branca \
            bs4 \
            datascroller \
            folium~=0.12.1 \
            geopandas==0.10.2 \
            matplotlib \
            numpy \
            pandas==1.4.2 \
            pycountry \
            pycountry_convert \
            requests \
            scipy \
            shapely \
            pytest>=5.0 \
            pandas-flavor \
            openpyxl \
            unidecode \
            openpyxl \
            lxml \
            colorama \
            tqdm \
            seaborn \
            IPython \
            pytest
      
      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install bokeh==2.4.0
          pip install branca
          pip install bs4
          pip install datascroller
          pip install folium~=0.12.1
          pip install geopandas==0.10.2
          pip install matplotlib
          pip install numpy
          pip install pandas==1.4.2
          pip install pycountry
          pip install pycountry_convert
          pip install requests
          pip install scipy
          pip install shapely
          pip install pytest>=5.0
          pip install pandas-flavor
          pip install openpyxl
          pip install unidecode
          pip install lxml
          pip install colorama
          pip install seaborn
          pip install tqdm
          pip install IPython
          pip install pytest


      - name: Run tests
        run: pytest
